# Site settings
title: Anish Kannan
email: anishkannan3210@gmail.com
description: "Anish Kannan's portfolio."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: http://facebook.com/john.do.921230
  - title: github
    url: http://github.com/anikan
  - title: email
    url: mailto:ankannan@ucsd.edu
  - title: devpost
    url: http://devpost.com/AnishKannan

# Postal address (add as many lines as necessary)
address:
  - line: UC San Diego

# Build settings
markdown: kramdown
permalink: pretty
